#include <stdio.h>

int main(void) {
  puts(
      "OOkxxkkxxxxkxxxkO0KK0KKKKK00000KKK0KKK00KKXXKXXXXXXXXXXKOxol:;,,,,,;:"
      "cclloxxdoodxxxxkkkkkkkkkkkkOOOOOOOOkkkkkkxxxxxxddooc:;,''''''''.......''"
      "'''''....',::::::ccccccllllllllllllllllllllllllllllllllllll\n"
      "kkkkkxddddxxxxxkOO00000000O0000KXKKKKKKKKXXXXXXXXXXNXX0Oxxddol:,',;:"
      "clodddxkxxxkkkkkkkOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkxxdddol:;,'.'''''..'''''"
      "''''''''....',;:::ccccccllllllllllllllllllllllllllllllllllll\n"
      "ddxxxddddxddddddxO000OO000OO0000KKXXKKXKKXXXXXXXXXXX0OOkkOkkkxoc:"
      "clddxxkkkkkkxkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkxxxxdolc:;;;;,,,,,,"
      ",,,,;;;;;,,,'......,:ccccccllllllllllllllllllllllllllllllllllll\n"
      "kxxxddddxxddxxdoxk0KK00KK000K000KKKKKKKK0KXXXXXXXXK0OkOOOOOOkxxxxxxxxxxx"
      "xxxkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkxdddolllcccllccccccccc"
      "cccc::;,'....';cccccllllllllllllllllllllllllllllcccccccc\n"
      "kkxdddxxxxxddooddxk0KKKKK00000KKXXKKKKK00KXXXXXXK0OkOOOOOkkkxxxxxxxxxxkk"
      "kkkkkkkkkkkkkkkOOOOOOOOOOOOOOOkkkkkkkkkOkkkkkkkkkxxxxxdddddodddooddddddd"
      "ddddoolc:,....':ccccllcllllllllllllllllllccccccccccccccc\n"
      "kkxddxkkxxxxxdodooxO0000000000KKKKXXXKKKKKXXXXXKOOOOOOOkkxxxdddxxxxxxxkk"
      "kkkkkkkkkkkkkkkkkOOOOOOOOOOOOkkkkkkkkkkOOkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxx"
      "xxxxxxddol:,'..':cccclllcllllllllllllllllccccccccccccccc\n"
      "OOOOOOOkxddxxxdxxxk00OOOOO00000KKKXXXKK00KXXXK0OOOOOOkkxddddddxxxxxxxxkk"
      "kkkkkkkkkkkkkkkkkkkOOOOOOOOkkkkkxxkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxx"
      "kkkkkkkxxxol:,...;clcccccllllllllllllllllccccccccccccccc\n"
      "00000OOOOkkkkkkxxxO000OOOO00000KKXXXKK000KXXK0OOOOOkxxdddddddddddxxxxxkk"
      "kkkkkkkkkkkkkkkkkkkkkOOOOOOkkkkxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
      "kkkkkkkkkkxxol;'..,:cccclclllllllllllllllccccccccccccccc\n"
      "KKK00OOOOOOOOOOkxxO000OOOOO0K0000KKKKK00KXX0Okkkkkxxddddddddddddddxxxxxk"
      "kkkkkkkkkkkkkkkkkkkkkkOOOOkkkxxxxxxkxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
      "kkkkkkkkkkxkxxoc,...;ccclllllllllllllllllccccccccccccccc\n"
      "KKKKKKK00OOOOOkkkkkOOOOkkkkO0K000000KKK0K00kkkkkxxddoooddooodddddddxxxxx"
      "kkkkkkkkkkkkkkkkkkkkkkkkkkkxdooxxddxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
      "kkkkkkkkkkkxxxxdl;'.,clccccccccclllllllccccccccccccccccc\n"
      "KKKKKKK000OOkkkkkkkOOkkkxxxkO0KKKKKKKKK0OOkxkkkxdddooooooooooodddddxxxxx"
      "kkkkkkkkkkkkkkkkxxkkkkkkkkxdoccdxdoxxxkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOO"
      "OOOkkkkkkkkkkxxddl;'';ccccccccccclcccccccccccccccccccccc\n"
      "KKKKKKK00000OkkkkkkOOkkkkkkkkO00KKKKK0Okxxxdxxdoooooooooooooooodddddxxxx"
      "xxkkkkkkkOOOkkxxxxxxxxxxxkkdl;;"
      "ldoodxxxkkkkkxxxxxkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOkkkkkkxxxdol:'':"
      "cccccccccccccccccccccccccccccccc:\n"
      "KK00KKKKK00OOOkkxxkOOOkkkkOOOOO000KK0kxdddddddooolloooooooooooooddddxxxx"
      "xxxkkkkkkkOOkkxxxxxxxxxxxkxl:;':"
      "odooxxxxkkkxxddxxkxxxkkkkkkkkOOOOOOOOOOOOOOOOOOOOkkkkxxxddol;',:"
      "ccccccccccccccccccccccccc:cccccc\n"
      "0000KKKKKKOkkkkxxxkkOOOkkkOO00000KKK0kxooooodoolllllllollllllooooodddxxx"
      "xxxxxkkkkkkOkkxxdddddddddxdc:;';"
      "ldlldxdxxxxxdddxxxxxxxkkkkkkOOOOOOOOOOOOOOOOOOOOOkkkkxxxxdooc;';:::::"
      "ccccccccccccccccccccccc::::\n"
      "00000KKKKKK0OkkxxxkkkkkkkkkO0000KK0000koloooooollccccllllllllllooooodddd"
      "xxxxxxkkkkkOkkxddoooooodddl::;',"
      "cdlloddxxxxddoddxxxxxxxkkkkkkOOOOOOOOOOOOOOOOOOOOOkkkkxxxdooo:,,::::::"
      "ccccccccccccccccccccc:::::\n"
      "000000000KKKK0OkxxxxxkkkxxkO0K00KK0000xolooollllccc::"
      "cclllllllllllooodddddxxxxxkkkkOOkxdollllooooo:,''.':"
      "olcodddddddooodxxxxxxxxxxkkkkkkOOOOOOOOOOOOOOOOOOOkkkxxxxddol;',;::::"
      "ccccccccccccccccccc:::::::\n"
      "0000KKK00KKKKK0kxdddxkkxxkkO0000KK0OOxdooooolllllc::;::"
      "cccclllllllloooooddddxxxxkkkkkkkdoccccllll:..   "
      ".:lcclodoooooloodxxxxdxxxxxxxkkkkkkkOOOOOOOOOOOOOOOOkkkkxxxddolc'',;::::"
      ":ccccc:::::::::::::::::::\n"
      "O00000K00KKXKK0OxdodxxxxkkO000OO0000Oxdoooolllllcc::;,,;"
      "ccclllllllllllloooodddxxxkkkkkkxoc;;:cccc;.    "
      ".;:;:lloooollloddxxxddddxxxxxxxxxkkkkkOOOOOOOOOOOOOOOkkkxxxddooc,.',;;::"
      ":::::::::::::::::::::::::\n"
      "kO00000OO0KKKKK0OkdodxxkkkkOOOOOOOO00kdooollccccccc:;,.';:"
      "ccllllllllllllllooodddxxxkkkkkdl;,;::::'     "
      ".,,,:clooolllloddddddoodddddxxxxxxxkkkkkkkkkkkkkkkOOkkkkkxxddool;..',;;;"
      ";::::::::::::::::::::::::\n"
      "kxkOOOOOOO00KKK0OkxxxxxxxxxkkOOkOOO00kdodolc:::cccc:;'...;"
      "cccllllllllllllllloooddxxxkkkkxo:,,;:::'     "
      ".,,,:lllollllloodddoooooodddddddxxxxxxkkkkkkkkkkkkkkkkkkkxxddlll:'.',,,,"
      ";;;;;;;;;:::;;;::::::;;;;\n"
      "OkxdxkOOOO00000OkkxxxdoodxkOO0OOO00K0kdooolc::;:ccc:,'...,:"
      "ccllllllllllllllllllooddxkkkkxdl:,,;;;.    "
      "..,,;clllllllllooddooolloooddddddddxxxxxxkkkkkkkkkkkkkkkkxxxdolcc:'..'',"
      ",,,;;;;;;;;;;;;;;;;;;;;;;;\n"
      "00OxxxxkkkOOO000OOkkxdlcloxkO000000OOxollllc:;,;:c:;'....':"
      "cccllooooooolllllllllooddxkkkkxdl;,,;,.  "
      "...',;:clllllllloodddooooooooooddddddddxxxxxxxxkkkkkkkkkkkxxdddollc;'.',"
      "'',,,,,;;;;;;;;;;;;;;;;;;;;;\n"
      "000OkxdxkkkkkOOOOOOkxdoccodxxkOO00OOkxoccccc:;',;;;'......;"
      "cclloodddddooocclooddddoodxkkkkxdl:;;,'..'',,;::"
      "ccclllllooddddoooooooooooddddddddxxxxxxxxxkkkkkkkkxxxdoolccc;'.,cc;,,,,,"
      ",,,;;;,;;;;;;;;;;;;;;\n"
      "000OkddxkkkOOOOOOOkkxddolodxxxxxkO0O0Okoc:::;,'',,,.....  "
      "'clloodddddddol:coxxxkkxdddxxkkkxxdocc:;;,,,,;::"
      "ccllllllloodddoooooooooooooddddddddxxxxxxxxxxkxxkkxxxdoolcc::,..,okdc;,,"
      ",,,,,,,;;;;;;;;,,,,,,,\n"
      "000OxdooxxkkkO00OOOkxddollodxxxdxkkOOOkdc:;,,,'',,'.....  "
      ".:ooodddddddol:;:oxkkkkkxxxxxkkkkxxdolc:;;;;::"
      "cccllllccllloooooooooooooooooooddddddxxxxxxxxxxxxxxxxxdolcc:;;,'..;"
      "dkOko:,,,,,,,;;;;;;;;,,,,,,,,\n"
      "000OxdooodxxxxOOOOOOkkxdlllodxkkkkOOOkkxl;;;,''',,'.....   "
      "'cooodddddolc;,,;"
      "cdxkkkkxxxxkkkkkkxxdolcccccclllllcccccclllllllllllllooooooooodddddddxxxx"
      "xxxxxxxxddollc:;,,,...;okkOOxl;,,;,,,,,,,,,,,,,,,,,,\n"
      "kOOOkxdooodddxkOOOkkkkxxdollodkOOOOOOOOkdl;,'',,,,'.....   "
      ".:ooooooooll:;,,''"
      "cdkkkkkkxxkkkkkkkkxxdooolllllllccccccccccllllllllllooooooooooddddddddddx"
      "xxxxxdddoolcc:;,,'...,lkkOOkkxc;,,,,,,,,,,,,,,,,,''\n"
      "ooddxdoooddddxxkkkkkxxxxxdolcldxkkkkkkOkkxl;',',,,'....   "
      ".':coollclccc:;;;,,"
      "cdxxkkkkkkkkkkOOkkkkxddoooolllcccccccccccccclllllllloloooooooodddddddddd"
      "ddddddooollcc:;,'....;oxkOkkOOko:,,,,,,,,,,,,,,,'''\n"
      "oooooooooddddddxxkkkkkkkxdoc:clddxxxxxxdddoc;'.'','....   "
      ".;ccll::;;;;,,,,;:"
      "codddxkkkkkkkkkkkkkkkxxdooolllllcccccccccccccccllllllooooooooooodddddddd"
      "ddddddoooolcc:;,'....,ldxkkkOOkOOxl;,,,,,,,,,,,,''''\n"
      "looooooolooooooddddxxxkkxddolccloddddddddddl;'...'.....   "
      ".,:lllc:;;,,,'',:"
      "cloooddxxkkkkkxxkkxxxxddoollllllcccccccccccccccclllllllooooooooooooddddd"
      "dddddooooolc:;,,'....,cdxxkkkkkOkOOkdc,,,,,''''''''''\n"
      "cllloooollllllooooooodddddddolc::cloooddddoc:,,'........   "
      ".;clllc::;;,''';:clllooddxxxxxxxxxddoolcc::::::::"
      "ccccccccccccccccllllllllloooooooooodddddddooooollc::;,'....;"
      "ldxxxxkkkkkkkkOOxo;,',''''''''''\n"
      ",;;::::cccccllcllloooddddoddoool:::cclllllllc:;,...........',;:cc:;;,,'."
      "..';::cclloddxxxddoollc:;;,,,,,,,,;;;:::::::::"
      "ccccccccllllllllooooooooooddddoooooollcc:;,.....;lddxxxxxxkkkkkkOOkkdc,'"
      ",,''''''''\n"
      "...''''',,;;::::clooooooooooddddolccccccccccc::;'.........',,,,,,,,''..."
      "...',;;:cclooooollc:;,'.......''',,,;;;:::::::::::::"
      "cccccllllllllllooooooooooooolllc:;,'....';lddddxxxxxxkkkkkkkkOkxo:,,,'''"
      "',''\n"
      "::;;;;;;,,,;;;;;::cllllooloooooooooollllllllccc:;'.''''''''''''''''....."
      "...'',,,;::cc::;;;'..............''',;;;::::::::::::::"
      "ccccccllllllllloooooooooollc:;,,'...';lddodddddxxxxxxkkkkkOOOkkdc,''''''"
      "''\n"
      "oooooodoooooooooooooooooolloooolllloooooooollccc:,''..'''''............."
      "...',,,,;,,,,''''..................',,;:::::::::::::::::"
      "ccccccllllllllllooooollc::;;,'...,coddodddddddxxxxxxxkkkkkOOkOxl:,''''''"
      "\n"
      "oooooooddddddddddddddddddddddddoooddddddddddooolc;,''..................."
      "...',,,,,,,,,,,,'...''.............',,;:::::::::::::::::::"
      "ccccccclllllllllllllccc::;'.';cloddoodddddddddxxxxxxxkkkkkOOOkdc,'''''\n"
      "llllloooooooddddddddddodddddddddddddddxxxxxxxdddooll:;''...............'"
      "'',,,;;;;;;;;;,'....''..............',;::::::::::::::::::::"
      "ccccccccllllllllllcc:::;'.':oooooooooooodddddddxxxxxxkkkkkkkkkxl;''''\n"
      "llllllooooooooodddddddddddddddddddddddddxxxxdddddddddoolc:;''......'''',"
      ",,;;;;::::::;,'...'''... "
      "...........',;:::;;;;;;;;;;;;;:::::cccccccccllllllllcc:;,',:"
      "clooooooooooooooddddddxxxxxxxkkkkkkkkko:,''\n"
      "llooloooooooooooooodddddddddddddddddddddddddddddddddddddxxddoc:;,,''''',"
      ",,;;::::::::;,........    "
      "..........'',;:;;,''',,,,,;;;;;:::::ccccccccllllllc::;,;:"
      "ccllooooooooooooooooodddddxxxxxxkkkkkkkkkxl;'\n"
      "cllllllooooooooooooooddddddddddddddddddddoooddddddxdddxxxxxxxxxxdolc:;,,"
      ",,,;;;::::::;,........    "
      "...........',;;;,,'''',,,,,;;;;:::::::ccccccclcccc::;::"
      "cccllllllllloooooooooooodddddddxxxxkkkkkkkkkko:\n"
      "ccllllllloooooooooooodddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxdoo"
      "cc:;;;;;;;;;;,........   "
      ".............',;,,,''''',,,,,;;;;:::::::cccccclcc::::::"
      "cccllllllllllllllllloooooooodddddxxxxxxxkkkkkkkd\n"
      "llllllllllooooooooooodddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxx"
      "xxddolc:;;;,,'........ "
      "...............',,''''''''',,,,,;;;;::::::ccccccc:;;;:::"
      "ccccccllllllllllllllllloooooooddddddxxxxxxkkkkkxx\n"
      "ccccccllllllllloooooooooooooooooooooooddddddddddddddddddddddxxxxxddddddx"
      "xxxxxxddolc:;,'''''....................'''......''',,,,,;;;;:::::::::::;"
      ";:::::::cccccccllcllllllllllllloooooooddddddxxxxxxxkkkxx\n"
      ":cccccclllllllloooooooooooodoooooooooodoooddddddddddddddddxxxxxxxxxddddd"
      "dddxxxxxxxxxdoc:,''.......''''.'''....'......''''''',,,,;;;;;;;;;;;;;;;;"
      ";:::::::cccccccccccccclllllllllllllooooddddddxxxxxxxxkxx\n"
      "ccccccccclllllloooooooooooooodddooooodddddddddddddddddddxddxxxxxxxxxxxxx"
      "ddddxxxxxxxxxxxdolc;,,,,,,,;;;;;;;;,;;;;;,,,,,,,,,,,;;;::ccllc;;;;;;;;;;"
      ";;;::::::::::ccccccccccccccclllllllloooooddddddxxxxxxxxx\n"
      ":ccc:"
      "cccccllclllloooooollllloooooooooddddddddddddddddddddddxxxxxxxxxxxxxxxdxx"
      "xkxxxxxxxxxdddddolcc:cccclccllllllllooodoooooodddddxxxkkdl;;;;;;;;;;;;::"
      "::::::::::ccccccccccccccllllllllooooodddddddxxxxxxx\n"
      "ccccccccclllcllloooooooolllolllloooooddddddddddddddddddddddxxxxxxxxxxxxx"
      "xxxxxxxxxxxxkkkkxxddddddoollloooodoodxxdddddddddxxxxxxxxxxkxxkdc;;;;;;;;"
      ":::::::::::::::::::cccccccccccccllllllloooooodddddddxxxx\n"
      ":cccccllllllllllllooooollooooooooooooddddddddddddddddddddddddddxxxxxxxxx"
      "xxxxxxxxxxxxxxxxxxxdddooddddoodxxdddddddooooddddxxxxxxxxxxxxxxxdc;;;;;;;"
      ":::::::::::::::::::::::ccccccccccclllllloooooodddddddddx\n"
      ":::"
      "ccclllllllllllllllllllllooooollooooddoooooodddddddooooooodddxxxxxxxxxxxx"
      "xdddxxxxxxxxxxxxxxxdoooooddxxxxxdollloooooddddddxxxxxxxxxxxxxdc:;;;;;;;;"
      ";;::::::::::::::::::::::ccccccccllllllllooooooddddddd\n"
      "::::"
      "ccccccllllllllllllllllllllllllooooooooooooooodddddoooooddddxxxxxxxxxxxxx"
      "xdddxxxxxxxxxxxxxxxxxolllodxxdollllllooooddddddddxxxxxxxxxxxxdo:;;;;;;;;"
      ";;;:::::::::::::::::::::cccccccclllllllloooooooddddd\n"
      ":::::"
      "cccccclllllllllooooooooooooooooooooooddoooooooddddoooooddddxxxxxxxddxxxx"
      "xxddxxxxxxxxxxxxxxxxxdollloddolccclllloooooodddddddxxxxxxxxxxxol;,;;;;;;"
      ";;;:::::::::;:::::::::::ccccccccllllllllloooooodddd\n"
      "cccccccllllllllloooooooooooooooooooooooooooddddooooooooddddooddddddddxxx"
      "xxxxxxxddxxxxxxxxxxxxxxxxxxxxxdoooddolcclllllooooooddddddxxxxxxxxxxxdoc;"
      ";;;;;;;;;;;;;;;;;;;:::::::::::cccccccccccllllllooooooooo\n"
      "cccccllllllllllooooooooooooddoooooooooooooooddddddoooddddddddddddddddddd"
      "dddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddolccllllloooooodddddddddxxxxxxxxdl"
      "c:;;;;;;;;;;;;;;;;;;;::::::::::::ccccccccllllllllloooooo\n"
      "ccccccccllllllllooooooooooodoooooooooollooooddddddoooddddddddddddddddddd"
      "dddxxxxxxxxxxxxxxxxxxxxkkkxxxxxkxxddddddollllllllooooooddddddddddxxxxxxd"
      "doc;;;;;;;;;;;;;;;;;;;:::::::::::::ccccccccllllllllooooo\n"
      "ccccccllllllllloooooooooooooooooooooooooooooooodddoooddddddddddddddddddd"
      "dddddddddxxxxxxxxxxxxxkkkkxxxxxxxxxxxddddolccclllllloooooooddddddddddddx"
      "xddoc:;;;;;;;;;;;;;;;;:::::::::::::::ccccccccllllllllooo\n"
      "::"
      "ccccllllcclllooooooollllllllloooooooooooooooodddoooddddddddddddddddddddd"
      "dddddddxxxxxxxxxxxxxxxxxxkkkkxkkkkkxxxddoolccclllllloooooooodddddddddddd"
      "dddol:;;;;;;;;;;;;;;:::;:::::::::::::ccccccccllllllloo\n"
      ":::ccccccccccllloooollllllllllllllooooooooooooodddoooddddddddddddddddddddddxxddddxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkxdddolcccccllllloooooooooooodddddddddddol:;;;;;;;;;;;;;;;;::::::::::::::cccccccclllllllo	\n");

  return 0;
}
