#include <stdio.h>

int main(void) {
  puts(
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNWNNK00Okkxdxkkkkkkkkxooooool"
      "c;;;;:c::cllcccclllllcccc:::::;:;;;;;;;;:::"
      "cclooodddddxxkkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      "MMMMMMMMMMMMM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOkkkkkkkxoodxxxxkkkkkxdolllllc"
      ";;;;:c:::ccccccllc::;;,,;;;;;;;::;;;;:::::::"
      "clooooooooddxxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      "MMMMMMMMMMMM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kkkxdddddoooodxxdxxkkxxdlllllc:;"
      ",,;:::::cccclc:;;,,,,,,,,;;;;;;;;;;:::::::::"
      "cllllolllllloodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      "MMMMMMMMMMMM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkkk0KOxxddoodxdooddxxxdolllccc:;,"
      ",,;c:;:c:ccc:;,'',,,,,,,;;,,,,,,;;::"
      "cccccllllllllcccclllloodOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      "MMMMMMMMMMMMMMMMMMMM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkkOO0Oxdooodxxdllodxxxolccc:;;;,,"
      ",;::;::::c:;''''',,,'',,;,,,,,,;::cllloooooooooool:;;:"
      "cclooox0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      "MM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOkxxxddooddddoollodxdolc:::;;;,''"
      ";:;;:::cc:,'.'''',,'',,,,,,,,,;:ccloooddddddddddol:;'',;:"
      "codxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      "\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOkxddoooloodddolllllddl:::;;;;;,'',"
      ";;,,;;::;,'..''''''',,,'',,;;;:cclooddxxxxxxxxdddol;'.',;;"
      "coxk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0Oxddllllcclddooolc:cooc:::;,;;;,''',"
      ",',,,;:;'.....''''''','',;;:::cclooddddxxxxxxxxxddoc;'',;;;"
      "codk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kxdooolc:::ldooolc::llc:;;;,,;;,''',,"
      "''',;;;'......''''''''',;;::cccllooddddxxxxxkkxxxxdo:,'',;;:"
      "codx0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOddddkkolc::clooolc::ccc:;,,,',,,,''','"
      "''',;,'..........'''',,;::cccclooooddxxxxxxkkkkkkkxdl;'',,;;:"
      "lookKNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdodkKOdlc::clllolc:::c:;;,,''''''''''''"
      ".'',,'...........''',,;::cclllloooddxxxxxkkkkkkkkkkxdc;'',,;:"
      "llldOXWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkddkX0occc::looll::;:::;,,,'''''''......"
      "''','............',,;::cclllloooddddxxxxkkkkkkkkkkkkxo:,'',;:"
      "lccox0NWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKddx00o:c:::clolcc;;;::;,',,'..''........"
      "'','...........'',;::ccllooooooddddxxxxkkkkOOOkkkkkkkdc,'',;::::"
      "cdOXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOldO0dlccccccllcc:;,,;;,'''''............"
      "''''.........'',;:ccllooodddddddddxxxxkkkkkOOOOOOOOkkxl;''',;;,;:"
      "lxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
      "0XNWWWMMMMMMMMMMMMMMMMMMMMMMMMWklxOxlclcccccccc:;;,,;;,''''............."
      "'''.......'',;;:cllooodddxxxxxxxxxxxxxkkkkkkkkkOOOOOOko;'''''''';"
      "cokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
      "loxkk0NMMMMMMMMMMMMMMMMMMMMMMMNxlddlcccccc::cc:;;,,,;;'.'''............'"
      "''......',;;:cllooooooddddxxxxxxxxxxdxxxxxxxxkkkkOOOOOd;'''',''',:"
      "ldkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
      "cccllx0NWMMWMMMMMMMMMMMMMMMMMMWOoolcccccc:::cc:;,',,;,'..'.............."
      "'......',:cllloooooooooooddddddddxdddddddddxxxkkkkkOOOx;.''''..',:"
      "ldk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMWWMMMMMMMMMMMMMMMMMMMMMMM\n"
      "::::ccox0NWWWMMWWWWWMMMMWNNNWWMXkoccc:::::cc:;;,,',;,'.................."
      ".....',:clloolllllllllooooooooooodoooolllllloooddddxxkx;.'',,',,';"
      "cokOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMWWWMMMMMMMMMMMMMM\n"
      "::cccccld0XNXXXXKKKXNWWX0OOO0XNXOdcccc::::::;,,,'',,,'.................."
      "....,:cclllccc:::::::::ccclllllllooolcc:;,,,;;::ccloodd;',:cc;;;',:"
      "lxOXWMMMMMMWMWWMMMMMMWWMMMMMMMMMMMMMMMWWNXKK00KKXWMWNXXNWWMMM\n"
      ":::cllllodkO000OOOO0XXKOxkkOOOOkxxoccc:::::;,,''..','..'................"
      "...,:cc::;;;;,,,'''''',,;::cccllllllc:;,,,,,,,;;:coooxd;.;coko,'.';"
      "cdkKWMMMMWWNNXXXNWWMMWWMMMMMMMMMMMMMWWXKOOO0OOOO0KK0OxkO0KXXX\n"
      ";:::cclodddxkkOOO00000Okkxkkkxxddxdlcc:::c:;''...''''..'................"
      ".',;::;;;;;,,,,'''''''',,,;::cllolllc;,'''''',,;;:loddx:.;lkKO;...';"
      "lx0XNNNNNXXNK0KXNWMWNNWMMMMMWNWMMMWKOOOkkOOxxk00Oxdooooodxxx\n"
      ":ccccllodoodxkOOOOOOkkxdxxkkxdddddddol:clc;,'''''''''..................."
      "',;;;;;;;;;,,,'''....'''',,;:clooddoc'.........',,:lodxl;clx0k;....':"
      "oxkkkkO0KXXKKXNWMMWNNWWNNXKOKNWMW0xxkOOOOxclk0koloolllllood\n"
      "cccccccclllloodddddooddooddddodooloddolll:,,,,,'''''...................'"
      ",;;;;;;,,'...............',;:coddxxd:.....'''',;:ccloxkdlllddc'.....;"
      "coddddxkOOkkkOKXXXKOO0kxxdooxO0K0doxxkxxdoclolc:cc:::lllloo\n"
      ";:::::::ccccllooollcloddddooooolccldddolc:;;;,''......................',"
      ";;,,,,'.........'','..'''',:cldxxkkxl;,,,,;:::cloxxxkOOkolll;.......,:"
      "lllloollllollodddddoooooc:cooddoc:looolccclc;;::;;;:cccclc\n"
      ":;;;;;:::cccccccc:::cclllccclollloddoolc::c:;'.......................',:"
      ":::;;,,,,,,,,,,;;;;;,,,,,;:clodxxkOOdc;,;;;;:ccloxkkO00Od::;..',,...;ll:"
      ":ldolloddddooooddooodoc:cloolc:::cllc:::cccc::;,;:cc::::\n"
      "::::;;:c:::ccc:::::cccccc:::cccloddollc:ccc:,'.......................';"
      "cllolllllcc:;;;,;;;;;;;;;:cloodxxkkOOkdlcccccllodxxkOO000d,.',;:;'..,"
      "clc::lddlloodxxdollllccclc:;;,;:cllllcc::;;;::::::;;;;::::::\n"
      ";;;;,,;;;;;::::;;;;:c:::::::::cloooolc::lll:,........................,:"
      "looddddddooolcc:::::cccclloodddxxkkkOOkkkxxxxxxxxkkOOO000o'';:;,..';:cc:"
      ";;:clccllllllcc:::::::;;;,,,;:cccc:;;,;;,,,,',,,,;;;::;;;\n"
      ";,;;;;,,,;;;;:;,,,;cc:;;;,,;;;;:coolc:;cllc;'........................,:"
      "loodddddddddddoooooooodddddddddxxkkkOOOOOOOOkkkkkkOOOO000l,;:,'',;:c::"
      "cc;;;;;::cc:;;;;:;;,,,,,,'''''',;;;;;;;;;,''''''''',;;;;;;:\n"
      ";',;;,,''',,;;,,,;;::::;,,,,,,,;:cllc;;clc:;'........................,:"
      "coodddxxxxxxxxxxxxxddxxxdddddddxkkkkOOOOkxxxxkkkkkkkOOO0Ol,,,;;:c::::c:;"
      ",'',,,;:::;,,,;;;,,,,,,'''..',,,;:;;,,,''''''''''',,;;;;;\n"
      "ool;,''...',,,''',;:::::;;,,'',;:cclc;;clc:,'.............   "
      "........,;cllodddxxxxxxxxxxxxxxdoooddddddxxkkkOOOOkdc:coooddxxxkkOOc';"
      "clc::;;;;;;,'..'',,;;;;,'',,;;;;,,,,''..',,,;,'''''''''''''''''',,,,,\n"
      ",coxxoc;,'.'''''',,,,,,,;;;;,',;cc:cc::cc:;,..............    "
      ".......,:clloddddxxxxxxxxdddolc:codddddddxxkkOOOOOOd;,;::clooddxkx:,,:"
      "cc:;;;;;;,'....'',;,,,''',,,,;,,,,''...',,,;,,,,''..''''..''',,,,,,,\n"
      "''',cdkOkoc;;:::;;,'...'''''''',;;;;:::cc:;,'..............     "
      ".....';clloooddddddooooolc:;,;ldxxxxxddxxxxxkOOOOxc,',;;:cclodxc,;;:lc:;"
      ",,;::;,'',,,,;::;;,,,,,,,,,''''''''',,;;;,;;,''..'''''',,,,;;;;;\n"
      ",',,'';ldO0Okdo:,,''..........'',;;,;;;:::;,'...............       "
      "..';:cllooollllllccc::;;,,,coooooollloolloddddoc:,,,,,;:cldd:;ccccc::;;:"
      ":::;;;::;:cllllcccc:::::c:;;;;::::cccc:;;,,,,,,,,,,,;;:::::::\n"
      "c;'',,'.':ox00Okdl:,'.'',''''''',;;;;;;;;;:;,''.............        "
      ".';cccllllcc::::::;;;;;;;;;;;;,,,,;;::::clooddol:;,,,,;:oxo:::ccc:::::::"
      "::;:looccoddddoolcclccloc;::clc:clcllc:;,;;;;:;;;,;;::::::::\n"
      "oc;,',,''..,cokO00kxoc;,,,,''''',,;;;;;;;::;;,,''................   "
      "..;cccccc::::;;;;;;;,,;;:::;,,''''',,,;;:loddddol:;,,;;:dd:,;;clc;;::::;"
      ":::ldOkddkOOO0OOkkkOOkOOxooxkkdccloddol:;:cc::::;;;:cclloooo\n"
      "ddl:,',,'....';cdk000Okdoc;'''''',;;;;;::cc::;,,'.............       "
      ".,:cccc::::;;;,,,,,,;;:ccc:::;,,,,,,;;:clodddol:;;;;;codc,',;clcclcllc::"
      "ccok0OxxO0O0KKKK00KXKXXOxk0XXOoldkkkxocclddllolc:cllodkkOkk\n"
      "xxdl:,'''..''.''';lxO00OOOxoc;;,',,;;;::::llc:;,,'.......   .         "
      ".;cccc:::;;;,,'''',;;::c::c:::;;;;;::ccccccllcccccclodl;',;:"
      "loxxxdxxoccloxO0000KKKKXXNXXXNNXNN0k0XNX0xxO000OkolxOOxxkxddxxxkO0KKK0\n"
      "ddddl;'''''..''''''';okO0OOOOkxdl:;;;;clclllcc:;;;'.'....              "
      ".;ccccc:::::;;,,,'''',,,,,,,,,,,,,;;;::clodddddddoddl,'',;:"
      "ok000OOOdlloxkO0KKXXXXXXXXXXXXXXXXK0KXXNX0OKXKKK0kk0KK0KKK000K0KKKXXXK\n"
      "xxdxdl:,''''..',,'...',:okOOkkO0Okxdlclooodoooc:cc,.''......           "
      ".';ccccc:::::::::::::::;;;::;;;;;;:clooddxxkkxxxdddo:,,:::"
      "lkKXXXKK0kxdkOO0KKXXXXXXXXXXXXXNXXXXXXXXXXKKXXXXXK00KXKKKXKKKKKKKKKKKKK"
      "\n"
      "xxddxdo:,..''''',,'..''.';lxO0OOOOOkkkkxxxO00koccc,''......    .        "
      ".,:cccc:::::::cccclllllcccccccccccllloodxxkkxxxxxdl:;:"
      "cccdKNXXXXXXK000KKXXXXXXXXXXXXXXXXXXXNXXXXXXXKXXXKXXXKKXXXKXKKXKKKKKKKKK"
      "KK\n"
      "xxdddddoc,....'',,,'.',,'':oddxkOOkkkOOOkk0KKOdol:,'......   ....   .   "
      "..,;:c::::::::ccllllllllllcccccc::"
      "cccllodxxxkkxxxxoccldxxOXNXXXNXXXXKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXXXKKKKKKKKKKKKKKKKK\n"
      "kxxdoooooc,..'.'',''.',,,''lxxoloxOOOkkkkOOOkxdlc;,'..............',,'.."
      "..',;:::::::::cclllllllcccc::::::::"
      "ccclooxkxkkxooddddkO00KXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXKKKKKKKKKKKKKKKKKK\n"
      "xxxdddoodo:.....'''..',,,,',oxo;.':okOOOOOkxxoc;,'.......',;;;;;;col::;,"
      "',,,,,::::c::ccclllllllcccc::::::cclloddxxkkkxc,';:"
      "cccllodxOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK"
      "KKKKK\n"
      "xxxxddoooo:'...''''...',,,;':xx;...,cdkkxdo:;,,'....... "
      ".;okkkkolol:::;;,,;:;,;;::cccccclllllllllllllllooodddxxxxkkkx:. "
      "...',;::::::"
      "cldk0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKK\n"
      "xxxxddooodoc:,'''''....',;c;':Ox,.',;cllllc;,'''........,lxxddocclc;::;:"
      ";;:c:;;;;::cccccllllooooooooooooodddddxxxxkkOx:'.   "
      "...',,;;;;;:"
      "cloxOKKXXXXKXXXXKXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK\n"
      "xxxddooooddolc;'..''....,;;,''ldc,:;:cccc:;;;,......  "
      ".':llcclcc:cc::::c:::c:;;;;;;::cccclllllloooooooooodddddddxxxO0KKOd:..  "
      " ....''''',;;;;:"
      "okKXKKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK\n"
      "xxxxdddooolodol;'.''....',,::,;c:clccc::;,''''..     "
      "..,:llcclllccccccclccccc::::;;,;;::cclllllllllllllllllllllooddkOkO0KKOo,"
      ".    "
      "........',,,,;lkKXKKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK\n"
      "xxxxddddooooddll:,''..',;clllcllcc:,;,,,'''''..      "
      ".,:clllllooollllclllcccccc:::;;;,,;;::clllccccccc:::"
      "cccccclccldkkkO00KKOd;...  "
      ".........'',;cx0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK\n"
      "kkxxxxxdddooodddoc;;:lodddddooolc:;'''...'''.....    "
      ".;clloooooddoooooooollccccc::::;;,,,,,;:::ccccc:::::::clldo,.:"
      "oxkkkO00K00Oo,...............:"
      "lldOKKKKKKK0KKKKKKKKKKKK0000000KKKKKKKK000000KK00000000\n"
      "kkxxxxdddddddddddoooddddooollccccccc:;,..........    "
      ".;cloooooodddooddooooolcccccc::::;;;,,,,,;;;;;;;:::cloddxkl..;"
      "cdxkxx0OOKK00kc.............;:"
      "cccok0KKK0000KKKKKKKKKK00000000000000000000000000000000\n"
      "kxxxddxxddddddooollllllllllccc:cc:::::;'..........   "
      ".:loodddddddddddddddddoolccccccc::::;;;;;;;;;;;:::clodddxd;..,:"
      "lxkkdk0O0000OOo'..........',;:"
      "ccclxO0KKKKK000000000000000000000000000000000000000000\n"
      "xxxoccloddddoooolllcccccccccc:::::::;;,''...... ... "
      ".':loodddddddxxxdddddddddolccccccc:::::::::::::::cclllooodc'..';"
      "cdkOxok0k00OOOkl'...........',,:"
      "cccokOO000000000000000000000000000000000000O00000000\n"
      "xxxdollc:cllloodooolllccccccc::::;,'................ "
      ".;odddxddddxxxxxxxxxdddddoolc:ccccccc::cccccccccccclllool;'..',"
      "coxOOddO0O0OOOkxc.  "
      ".........'.',;:clodxkOO000000000000000000000000000000OOOO0000000\n"
      "xxxxxdddol:::cloollllllllc:;,,''......................'"
      "lxddxxdxxxxxxxxxxxxxxxddddol::::cccccccllcclllllllllolc,'..',:"
      "ldkOkxkOOOOOOOkd:..  ... "
      "........',:codddkO0000000000000000000000000000OOOOOOOOOOOO\n"
      "xxxxxxxxdddl;,,:cccc:::;,'............................."
      "cdxxxxxxxxxxxxxkxxxxxxxxxxxolcc:cccccclllllllllllllool:,'..',,:"
      "dxOOOxO0OOOOkkko;..  ..  "
      "..........,:looddkO00OOO000000000000000000OOOOOOOOOOOOOOO\n"
      "xxxxxxxxddddl,.',,,,'..................................;"
      "oxxxxxxxxxxxkkkkkkkkkxxxxxxdollcccclllloooollllllodoc:,'...;;,"
      "cxkO0OO000OOOkkdl;..  .   "
      "...........,:loodkO0OO0000000000000000OOOOOOOOOOOOOOOOOO\n"
      "xxxxxxxxdddo:'.........................................."
      "lxxxkxkxxxkkkkkkkkkkkkkkkkkkxddooooooooooooooooooodoc:;,'..,c,,"
      "okO000000OOOOkxoc;'.     "
      "............,cooodkOOOOOOOOOOOOOO0000OOOOOOOOOOOOOOOOOOO\n"
      "xxxxxxxddddo;.''........................................;"
      "xkkkxkkkkkkkkkkkkkkkkkkkkkkkkkxxxddddxxxxxxxxdddddol:;,''.,lc,:"
      "dk000000OOOOkkdoc;'.     "
      "...........':loloxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n"
      "xxxxxxxddxdo,.''........................................'"
      "okkxxkkkkkkkkkkkOOOOOkkkOOOOOOkkkkkkkkkkkkkkxxxxddolc:;''''cdc:"
      "ldO000000OOOkkxdoc;'.    "
      "...........';cllldxkkOOkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n"
      "xxxxxxxxxddl,.'''........................................"
      "lOkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkxxxxdolc:;,,'':"
      "xxoloxOKK000OOkkkkxdol:'.    "
      "...........,:cllllodxkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOO\n"
      "xxxxxxxxxddl,.',''......................................."
      "lkOOOkOOOOkkkkOOOOOOOOOOOOOOO0OOOOOOOOOkkkkkkkkxxdollc:;,,,;"
      "dOxddok0KKK00OOOkkkxdol:'.   "
      "...........,:ccclllloodxkkkkOOOOOOOOOOOOOOOOOOOOOOOOOO\n"
      "xxxxxxxkxdoc;'.'''......................................."
      "lxkkOOOOOOOOOOOOOOO0OOO00OOOOO000OOOOOOOOkkkkkxxxdoolc:;;,''"
      "o0Oxxxxk0KK000OOkkkxxddoc,.  "
      "...........,;:cc::cc::coxxxkOkkkkkkkkkkOOOOOOOOOOOOOOO\n"
      "xxxxxxxxdocc:,..''......................................'"
      "okkkOOOOOOOOOOOOO00000000000OO0000OOOOOOOOkkkxxxddollc:;;,'."
      "l00kkkxdx0KXK0OOOOkkxxxddl.   ...... "
      "...';:ccc::;;;;cllldkkkkkkkkkkkkkkkkkkkkkkkkkk\n"
      "xxxxxxxxolcc:;'.''......................................'"
      "okkkOOOOOOOOOOOOOO000000000000000000OOOOOOOOOkkkxdoolc::;;;;"
      "lO00kxkOxx0XKK0OOOkkkxxddd,   ...... "
      "...';;::c:;,'';:ccccokOkkkkkkkkkkkkkkkkkkkkkkk\n"
      "xxxxxxxdlccc:;,.........................................."
      "cxkOOOO000000OOOOOO0000000000000000000OOOOOOOkkkkxxddoolllc:"
      "ckKK0Ok0Odx0KK00OOkOkxxxddc.  ......  "
      "..,;;::::,'..,;;::::lxkkkkkkkkkkkkkkkkkkkkkkk\n"
      "dddxddoolc::::,'.........................................,"
      "okkOO000000000OOO000000000000000000000OOOOOOkkkxxxddoolcc:;:"
      "dKKK0OO0kdx0XK0OOOOOkkxxdo,.  .....  "
      "..,;;;,;;'...,;;:c:::lddxkkkkkkkkkkkkkkkkkkkx\n"
      "xxxxdoolc::::;;,.........................................'"
      "lxkkOO0000000000000000000000000000000OOOOOOkkkkxxdddollcc:;;"
      "o0XKK0OO0koxKXK0OOOOOkkxxd:.  ....   "
      ".',,;;,,,....,;:::;;;:lodxxxkkkkkkkkkkkkkkkkx\n"
      "xxxxdolcc:::;;;,'....................... "
      "................."
      "cdxkOO000000000000000000000KK000KK00000OOOOkkkxxddddolllc:::"
      "d0XXKKOO0Kxok0XK0OOOOOkdxd:.  ...    "
      ".',,;;;;,...',;;;;;::::::::cloxkkkkkkkkkkkkkx\n"
      "xxxxdlcc::::;;;;,'......................   "
      "...............:"
      "oxkO00000KK000000000000000KK000KKKKK000OOOOkkkxxddooollccc:"
      "o0KXXK0O0K0kdkKK00OOOOkxxxl'. ....  "
      "..',,;;;;'..''''',;::;,''''',,:ldxkkkkkkkkkxxx\n"
      "xxxdlccc::::;;;,,'......................    "
      "..............;"
      "ldxkOOO00KK000000000000000KKKKKKKKKK0000OOOkkkxxxddooolcc:;"
      "lOKXXXK000K0xdkKK0OOOOOkxxo,.   .   "
      "..',,;,;;.......',,,''''',,;:::ccodxkkkkxxxxxx\n"
      "xxdlcccc::::;;;,''..........     .......      "
      "............:lodxkOOO000KK0000000000000KKKKKKKK00000000OOkkxxdollcc::::;"
      ":xKKXXXKK00K0xxOKK0OOOOOkxd;.       "
      "..,;;;,,,............''',,;;:::::cloxxxxxxxxxx\n"
      "xxocccc:;;;;;;;;,'.........       ......       "
      "...........cdoddxkOO0000K0000000000000KKKKKKK0000000OOOkkkxxdollcc::;,,'"
      "l0KKKXXXKKKK0kxOKK0kOOOkxxc.       "
      "..,;;;,,'..........'''',,,,,,;;;:cllodddxxxxxx\n"
      "xolccc:;,,,,;;;,,'.........       ......        "
      "..........cxxddxxkOOO000000000000000000KK00KK00000OOOOOOOOOkkxxdollcc:;"
      "lOKKKXXXXKKKK0kk0KKOOOOkxxl.       "
      ".',;;;;;'.........'''''',,;:::::cclllllodxxxxx\n"
      "dlcc:::;;,,''',''''........       ......        "
      "..........:"
      "oxxdddxkOOO0000000000000000KKK00K000OOOOOOO000000OOkkxxxxxxooOXXXXXXXXKK"
      "KK0OO0KK0OOOkxo,      ..',,,,;,...............'',;::::::cclllloooodxx\n"
      "olc::::;;;,,''..'''..........     ......        ......   "
      ".:"
      "ddxxxddxkO0O0000000000000000000000OOOOO00000KKKKKK0000OOO0OkxOKKKXXXXXXK"
      "KXX0OOKXK0OOkxd;.     ..',,,,,'............'',,,;;;:::c:::;;,,,,,',:o\n"
      "lc::::;;;;,,,,''...............   ......          "
      "........;"
      "ldkkkxddxOO0O000000000000000000OOkkOOO0000KKKKKKKKKKKK0000OOkO00KKXXXXXX"
      "KXXXK00KK00Okxxc.     ..','',,'..........''''''''''','''',,;;:::c:::l\n"
      "c:::::;;;;,,,,,''..............      ...           "
      ".......'"
      "ldxkkkxdoxOOO00O0000O00OOOOOOOkkkkkOOO000KKKKKKKKKKKKK0000OOOO00KKKKKXXX"
      "XKXXXKKKXK0Okkxl.     ..',,',,......................'',;:ccccc::cccc:\n"
      ":;;:::;;;;;;,,,,'''....... ...         ....          .... "
      ".lkxkkkkkddxO00O0000000OOOOOOkxxxkkOOO00000000000000000000O0OOO00KKKKKKK"
      "KKKKKXXXKXXK0Okxo'     ..''''''.         .........'';::cccccclllllllll\n"
      ";;;;;;;;;,,,,,,,,'''......  ..         ......              "
      ":kkkkkkkkdoxOOOOOOOOOOOOOOOkkkxxxkOOO000000OOO00000000000O0OOOO00000KKKK"
      "KKKKXXXKKXXKOkko,.    ..'''','.      ..........'',,,,;::ccllllllllllo\n"
      ";;;;;;;;,,,,,,,,,''''.......           ........   .....   "
      ".,"
      "xOOOOOOOkdodkOxooddxkO00000OkxddxkOOOOOOOOOOOOOOOOOOOOOOOOkkkO000000KKKK"
      "KKKKKKKKKXX0Okd;.   ...''''''.          ....''',,,;;:::ccclllllllooo\n"
      ";;;;,,,,,,,,,,,,''''''....... .         .........   ....   "
      ".lkOOOOOOOkdodkx;..'"
      "lxO00OO0OkxxxxkOOOOkkkkkkkkkkkkkkkOOxxxddkOOOO00000000000KKKKKKKK0kx:.  "
      " ...'''',,...       ....',,;;:::::::::ccccllllllo\n"
      ";;;;,,,,,,,,,,'...............            .......   .....  "
      ".;oxkOOkOOOkdodkd,,"
      "ldxkOOkOOkxxkOOkOOOkkkxxxxddddddddxdololcokkOOOO0000000O00000KKKKKKOxc. "
      "  ...''''','...    ....'',;::::::::::::::cc:ccclll\n"
      ";;;;,,,,',,,,,'...............            ........   ....   "
      ".:odkkkkOOOOkodkxdxxxdxkkOOxxxxkkkOOkkkkxxxdollccccllc;:c:"
      "cxkxkkOOOOOO000O000000000KK0kc.   ...''''''..    "
      ".......',;:ccccccccccccccccllllll\n"
      ";;;;,,,,,,'','''..............              .......    ..   "
      ".,cloxkkkOOOOkddkkxkkxkkO00kkxdxxkkkkkkkkkxdoc:;;;;;,,,;;;"
      "lxxxxxkkkkOOOOOOOOO0000000K0Ol.   ......'''.     ..  "
      ".....,::cccccccccccllllllllll\n"
      ";;;;,,,,,,,,''''''............               .............   "
      "':lcldkkkkOOOOxxxxkOO00KKK00OOkkxxkkkOOkkxxdl;,,;,''',;,:"
      "dxxxxxxxkkkkkkkkOOOOOOOO0000Ol,.   .....'''..           "
      "..';::ccccccccccccccllllll\n"
      ";;;;;;,,,,,,,'''''...............              ..........     "
      ".;clloxkxxkOkOOkxkO0000KKKKKK00OOOOOOOOOkkxdc:;;,',;:;:"
      "odddxxxxxxxkkkkkkkkkkkkOOOOO0Ooc:'  .......'...       "
      "....''',,;;::cclllllcccllllll\n"
      ";;;;;;;,,,,,,''''''..............                .........     "
      ".':cloxkxdxO00Okxxk000KKKKKKKK000OOOOOOkkxdol:,,,;:"
      "ccoxxdxxxxxddxxxxxxxxxkkkkkkOOOOkxodc. .......'....    "
      "....'''''''',,,;::cclllllllllll\n"
      ",,;;;;;,,,,,,''''''..............                  ........   "
      "....';:ldxxddkOOOkxxkO0000KKKKKK000OOOkkkxxdol:;,;;:"
      "codddxxxxxddddddddddddxxxkkkkkOOkxoxd.  "
      "......'............'',,,,,,,,,,,;;::clllllllll\n"
      ",,,;,,,,,,,,,''''''...............                   .......  "
      "......,;:ldxdodkOOkxdxkOO000000000OOkkkxxdollc:;;;;:"
      "odddxxxddddddodddoodddxxxxxkkkkkxxdxk'   ........      "
      ".....';;,;;;;;;;;;;:::cclllllll\n"
      ",,,,,,,,,,,,,'''''''.............                     ......  "
      "..'',,,',;:oxxoodkOkxdodxkkkOOOOOkkkkxxdollc:;;:;;:"
      "oddddxdooooolloooooooddddxxxxkkkkxxdkO;   ........       "
      ".....',,,;;;;::::::;:::cccllll\n"
      ",,,,,,,,,,,,,,''''''.............                         ...  "
      "',,,;,,,;,;cdxdoodxkxdoooddxxxxxxxxxddolc:::::"
      "cclodddddoolooolllooolllooddddxxxxxkO0kxOO:   .............   "
      "....',,,,,,;;;:::c::c::ccclll\n"
      "',,,,,,,,,,,,,,,''''.................                      ..  "
      "':;;;;::;;,;:"
      "lodooloxkxollllooodddddooolccclooodddoooolllllllllloolccloooooddxxxxxOKO"
      "k00c.  ........'',c;.   ....'',,,,,,,,;;;::cccccccll\n"
      ",,,,,,,,,,,,,,,,''''...............  ..                    ..  "
      ".::;;::c::;;,;"
      "clooolloxxxdolccllooooooooooollooolllcclllllccllllclllllloodxkOOkxdxO000"
      "00l.   .......:c,,;''. ....''''''''',,,,,;;:ccccccc\n"
      ",,,,,,,,,,,,,,,,''''..............                          .. "
      ".:c::::cc:cc:;,,;clooolodxkxdoolc::cllooooc,,"
      "clcccccllollllolcccclllloddxkkOO0Okdx0KKK00o.   "
      ".......;lc;'.;;......''''''''',,,,;;::cccccc\n"
      ",,,,,,,,,,,,,,,'''''..............                             "
      ".,:::ccclccccc:,'.,:llolllodxkkkdolc::clol:;:clcclollllllccccc::"
      "cloxkOOOOOOkxxxxxk0KKK00x,  "
      ".........::c:.,c;......''''''',,,,,;;::cccccc\n"
      ";,,,,,,,'',,,,''''''..............                              "
      ".;ccccclllllllc:'.',;:cllllloxkkkxxddddolllc:clllllllcc:;;;;;"
      "coxkO0K00OOkkxdooxkO0K0000Ol. "
      "........';;;;..;c:.....',,',,,;;;;;;;;::ccccc\n"
      ",,,,,,,,,,,,,,''''''..............                              "
      ".':ccccllllloollc;'',,;::cccccldxddxxxxxdolcc:::::;;;,,',:"
      "coxO00000000OkxddodkO0KKK00000d' ....... "
      ".:c:;'.':l;....''..',;;;;;;:::::::::c\n"
      ",,;,,,,,,,,,,'''''''...............      ..                      "
      ".,clllllloooooool:;;;;;;;;::cccllodddxxxxxxdolccc:;;:"
      "ldxO00K00000OOkkkxdodxO0KKK0OOOOO0k, ....... "
      ".'cc:'....,,............''',,;::ccc::\n"
      ";;;;,,,,,,,,''''''''................      ...                     "
      ".;clllclooooooodlccc:::;;;;;::::"
      "clloooooddxxxxxkkO000KKKKKK00OOkxxdoodxxO000000Okk0OOOO;......... "
      ".',;'':;.',,..  ............',;:::::\n"
      ";;;;,,,,'''''.......................       ...                   . "
      ".:clllllooooddooollllcccc::;;;;;::"
      "cloddxxxxxkO0KKKKKKKKKK0OkxdollodxkO0000OOkxxkOOOO0O; .......  "
      "...,,,:c:,,;,.........'''',,,,;;;;;:\n"
      ";;;;;;,,'''........................         ...                  .  "
      "':loolloododdodddooooollllcc:;,"
      "codxxddooxkO000KKKKKKKK0OOxddoodxkO000000OkxxxxkOO0000: ......   "
      ".'....,cc:;;::,......',,;;;;;,;;;;;;\n"
      ";;;;;;;;,,,'''''''.................          ....                   "
      ".':loollodddddddddddddddoooolc:"
      "ldxxooodk00000000000K00OkxxkOO000000K000OkkkkkkOOO0000l... ..   "
      ".,c;'...',:c;;:,''...'',,,,,,,,,;;;;;\n"
      ";::::;;;;;;;;,,,,,''''''........              .....                  "
      ".':"
      "looloodddddddxxxxxxddooollloddddxkO000000OO00000OkOO0KKKK0000000OOOkkkOO"
      "OOOO00000o. ..   .. .clc,.....,;;'.'''.'',,,,,;;;;;;;;;;\n"
      ";;;::;;;;;;;;;;;;;,,,,,,''.......              .......                "
      ".':loooodddddddddddxxxxddollcclc:"
      "cxO000000OOOOOOOOOO0KK0000OOOOkkkkxxkOOOkOOkO00000d. .. . .. "
      "'ccc;'''.......'''''''',,,;;;;;;;;;;\n"
      ";;;;;;;;;:::;;;;;;;;,,'''.... ..  ....            ......               "
      ".;coooodxddxxddddddxxddollc:;;;;;"
      "clxO0000OOOOOOOO00OOOOOkkkxxxxxxxxkOOOOOkkkO000O0x' .....   "
      ".:cl;..';'.....''.''',,',,,;;;;;;;;;\n"
      ";;;;;;;;;;;;;;;;;,,,'......   ...........     .    ........            "
      ".'cooddxxxxxxxxxxdddolcc::::;;;;;;::"
      "oxO00OOkkkkkkkxxxxxxxddxkkkxxxkOOOOOkkkO0000O0k' ...     "
      ".';:,.,,,;:;'..''.',,,,,,,,,;;;;;;;;\n"
      ";;;;;;;;;;;;;,''...................''...........     .......            "
      ".,:loddddxxxxddolcc:::::::::::;;;:::"
      "clxOOkkkxxxxxxxxddddxxkkkxxdxkO0OOOkkOO0000O0x'   .   "
      "...',;,';c;,:c:,....''',,,;;;,;;;;;;;;\n"
      "::;;;;;,,,'............'''',''....',,''..',;,,,,'''..........           "
      " .'cloooodddolc::::::::cc::::::;;:;;::"
      "coxkkxxxdddddddddxkkOkxddxkkOOkkOkO000000O0k,         "
      ".,;,,';::;,::'.''.''',,,;;;;;;;;;;,,\n"
      "::;;,'..............,;;;;,,'...'',,;,,''';::::::::::;;;,'..........     "
      "  "
      ".,clllooc;;:::::::::::c:::::::;;;;;;::"
      "codxdddddddddxxkkxxxxddxxxxxxkOOO00000OO0Oc.    .   "
      ".;:,.,:::;,;,'''''',,,,,,;;;;;;;;;;,\n"
      ";,'..............',;:::;,,''.'',;;:;;,,,;:::;;;;::::::::::;,''',;;;;,,''"
      "....;:::cc:;;::::::cc:::ccc:::::;;;;;;;;::"
      "codxddxxxxxkkxxxddddddddddkkkkOO000OO000x,    .  "
      "..;:;',:::c:;'.'''''',,,,,;;;;;;;;;;;\n"
      "...............';;;;;;;;,'''',,;::::;,,;::::;,,;::::::::::cc::::::;;;;::"
      ";;;:,'';:;:::;::::ccc::::::::::::;;;;,;;;;;:"
      "coxxxkkkkxxddooddddooodxkkkOOOO00000OOOl.       "
      ".,:;'';::::;'....''',,,;;;;;;;;;;;;;\n"
      ".............',;;,,',;;,,'',,;;::::;,,;:c::;;,,,,;::::::::::ccc:::::::::"
      ":::;'.;:;;::;;;;:::::::::::::::c::;,,;;;;;;;;:"
      "lxkkxxxdddoooddooodxkkkkOOOOOO0000OO0x,       .;:,'',:;;;'.  "
      ".....'',,;;;;;;;;;;;;\n"
      "........',;;;,,'',;:;,'',;:::;,;:;,,:::::;;,,,,,;:::::::::cccc::::::::::"
      ":,',;:;;;;;;;;;:::::::::::::::::;,',,,,,,,;;:"
      "coxdddooooooooddddxxxkkOOOOOO0000OOOOc       "
      ".,;'..';;,,'.......'',,,,,,,;;;;;;;;\n"
      ".......',,;;;,,'',,;:;,',,;:::;;;;:;,;:::::;;,,,,,;:::::::::::::ccccc:::"
      "::;,,;:;;;;;;;:;;;;:::::::::::::::::,''',,,,,,,;;"
      "cooooooddddoollloxkkkkOOOOO0000OOO0o.     "
      "..,;'',,',;;;,',;;'...',;,,,,,,,,,,,,\n"
      "....'',,;;;,,,'',,;::;,,;::::;;;;;;,,:::::;;,,,'',,;::::::::;;;;::ccc:::"
      ":;;,,;::;;;;::::;;;;::::::::::;;::;::,'.',,,,,,,,,;"
      "cloooolllcccloxxkkkkOOOOOOO0OOO00x,      "
      ".;:,,;,',;;;;;:::;''',''',,;;;,,''',\n"
      "'',,,,,,,,,,''',,;::;;;::c::;;;,;;;,;c:;;;;,,,''',,;;::::::;;;;;;:::c:::"
      ":;;;;::;;;:::::::;;,;;::;:::::;;;;:::;;,'',,,,,,,,,;:clcc:"
      "ccccodxxxxkkOkkkOOOOOOOOOOk;     ..',',;;,,,;;;:cll:,,;:;;'...',;;;;,'\n"
      ";,,''.'',,''',,,;;:::::::::;;;;,;:;,:c;;;,,'''',,,,,;;::::;;;;;;;;;;;;;:"
      ":::::::::;;;;::::::;,,;::::;;;:;;;:::;;;,',,,,,,,,,,,,;;;::"
      "clodxxxxxkkkkkkkOOOOOOOOOk:. . ...,,.';;;,';;;:looc;';::::;,....',,;;\n"
      "'''...',,,''',,;:::::::;;;;;;;;;;;,;:;,,,,''',,,,,,,,;;;;;;;;;;;,,,'''''"
      ",,,;;;:::::::::::::;;,,;::;;;;:;;;;;;;;;;,'',,,,''''''',:"
      "llodddxxxxkkkkkkkkOOOOOOOOOk:.   "
      "..';,',;;;;,',:coooc,',ccccc:,......',\n"
      ".....',,,,'',,;:::;;,,,,,,,;;,,;::;;;,,,,'''',;;,,,,,,,;;;;;;;;,,'''...."
      ".''',,;:::::::::::;;;,'';::::::;;;;;;;;::;,..''''''''..',"
      "cdxddxxxxxkkkkkkkkkkOOkOOOkx;. .. "
      ".':,..,;;;,',ldxdoc,';cllllc;'.......\n"
      ".....',,,,',,;;:;;,,,,,,,,,,,,,;c:;,,,,,,'''',,,,,,,,,,,,,,,,,,'''......"
      "....'',;;;:::::;::;,,,'..,::::::::;;;;;;;;;,....'''''....':"
      "odxxxxxxxxxkkkkkkkkkkkkOkx;......';,..'','.',;lol:...;cllllc;''......\n"
      "...''',;,,,,;;;;;;,,,,,,,,,,'',;;;,',,,,,'''',,,,,'',,,,,,,''''''......."
      ".......'',;;:::;;;;,,''...,:cc::::::::::::::;......''.....':"
      "oddddxxxxxxxxxxkkkkkkkkxo:'.....','.,''''','..''...';clllol;'''''',,\n"
      "..',,;;,,,;::;;,,,,,,,,,,,'..',,,,',,,,,''''''''''',,,,,,,'''''........."
      ".........'',,;,,''''......';;::::::::::::c:;'..........'..,"
      "cododddddxxxxxxxkkkkkkxd;,:.....'''';;,',;;,..''..';:cllloc;'',;,;;;\n"
      "...',,;;,;;;;;;,,,,,,,,,,'''.',,,,,,,,,,,''',''''''',,,,,,,'''''........"
      ".................................''''''''''''..............;"
      "coddddddddxxxxxxxxkkkxxc..,;....,'.,,;;',;,''.',,'',;cllolc;,,,,;;;,\n"
      ",..',,,,,,;;,,,,,,,,'''''''''',;,,,,,,,'''',,,'''''',,,''''''''........."
      "......................................................',,:"
      "cllooddooddddxxxxxxxxxxxl.. .,'...,,',;,;,,,;,'''',,,',;:clc:;;,'',;;;\n"
      "ollc:,''''''''''''''''''''''.',,,,,,,,,''',,,,''''',,,,,'''''''........."
      "....................................................';:"
      "cclllloooodddddddxxxxxxxxxo, .. "
      ".'......':;;;,','','',,,,,,,,,;,,;;,'',,;\n"
      "ooodolc:;,'...''''''''''''.'',,,,,,,,,,,,,,,,,,''',,,,,,'''''''''......."
      "........................''.......................',;:::"
      "ccllllloooodddddddxxxxxxxoc;'..  "
      ".'......;;;;'''.',,'',;,,,'.',,,,,,,'','\n"
      "ooooooddol:,,''''',''''''..',,,,',,,,,,,,,,,,,,,,,,,,,,''''''..........."
      "....................''...''....................',;;:::::"
      "cccclllloooddddddddxxxdo:',,... "
      ".'.......',,'...''.',,,,,,...,,,;,,,..''\n"
      "ooooooddol:;;,''',,''''''',,;,,''''',,,,,,,,,,,,,,,,,,,''''''..........."
      ".....................'''....'.............'''',,;;;;;::::"
      "cccclllloooooddddddddl:,,,,...  "
      "...,',,...';;..''''....''...'..'''.....\n"
      "oooooddxoc;,,''.'''''','',;;,''''''''''',,,,,,,,,,,,,,''''.............."
      ".......................''.............''''''',,,,;;;;;::::"
      "cccllllloooddoddddo:;;,,,'...  ...'',,'....''';;;,'..,,'''''''''''''..\n"
      "ooddddddo:,,,'''''''.''',,;,'.........''''',,,,,,,',,,'''..............."
      ".................................'',,;;;;;;;,;;;;,;;;;;:::"
      "cccccllolloooooool,.',;;;'...  ...'',;,'''....,;;;,'',,..,,''',,,'','.\n"
      "oooddddol;,,,''.''''....''.................''',,,,,,,'''................"
      "...........................'',;,,,,,,;:::::::::::;;;;;;;;::"
      "ccccllllllooooc;,'..',;;,.... ...'',;;;'',....,;::,'''..',,''',,','..\n"
      "ooooddooc;,,,'.'''''..........................'',,,,,''................."
      ".................      "
      ".....'',;;;;;;;;::::::::ccccccc::;:::ccllllllllc::,...'''',;,'... "
      "...'',,,;,,,'.....,;:;'..',,,,''',,,'..\n"
      "dooddddlc;,'''''','''............................'',''.................."
      "...........             "
      "..''''',,,;;;;;;::::c:::ccccccccc:::ccc:ccc::;,'','...'''''''... "
      "....,,,,'',,'',....';:;'.,,,,,,'',,,'''\n"
      "ooodoool:;,'''''',,'''.................................................."
      ".......                  "
      ".'''''',,,;;;;;::::cc::ccccccccccccc:::;,'..''..','...','.''...  "
      "...,'''...'.''.....',:,',,,,,,',,,,.',\n");

  return 0;
}
