#include <stdio.h>

int main(void) {
  puts(
      ".............'''...'"
      "cxOOOOO000000000000000000000000KKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
      "............''''...'"
      "cxOOOOO000000000000000000000000KKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
      "............''''...'"
      "cxOOOO0000000000000000000000000KKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXXXXXKKKXXKkxk00KK00KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
      ".............'''...,"
      "cxOOOO000000000000000000000000KKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXKKkoc:cdkd:,:"
      "odxdlclxKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXXXXXXXXXXXXXXXXXX\n"
      ".............'''...,"
      "lxOOOOO00000000000000000000000KKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKOxoo"
      "ddolcc;....''...';c:'..;"
      "x0KXXXXXXXXXXXXXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXXXXXXXXXX\n"
      ":;;,''.............,"
      "lxOOOOO00000000000000000000000KKKKXXXXXXXXXXXXXXXXXXXXXXXXXXKK0KKOo:,..."
      "..........       "
      "......."
      "ck0KKKKKKKKKXXXXNXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "XXXXXXXXXXXX\n"
      ",;;;;;,'.......'...;"
      "lxOOOOO00000000000000000000000KKKXXXXXXXXXXXXXXXXXXXXXXXXXXKo,,co:.     "
      "                      "
      "..'"
      "cxkkkO0K0OOKXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNXXXXXXXXXNNNN"
      "NNNXXXXXXXX\n"
      "'...'..............;"
      "okOOOOO00000000000000000000000KKKXXXXXXXXXXXXXXXXXXXXXXXXXKx;. ...      "
      "                         "
      ".'::,,"
      "coxdx0KKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNNXXXXXXXNNNNNNNNNXX"
      "XXXXX\n"
      "'''''.............';"
      "okOOOOO00000000000000000000000KKKXXXXXXXXXXXXXXXXXXXXXXXXOl..           "
      "                           "
      "......';"
      "okO0KKXXXXXNNNXXNNNNNNNNNXXXXXXXXXXXXXXXXXNNNNNNNXXXXXXXXXNNNNNNNXXXXXXX"
      "X\n"
      "''''.........'...',:"
      "okOOOO000000000000000000000000KKKXXXXXXXXXXXXXXXXXXXXXXKk;.             "
      "                                 "
      "..';"
      "lk0OkOKXXNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      "\n"
      "'''''.......'''',,;"
      "cdkOOO000000000000000000000000KKKXXXXXXXXXXXXXXXXXXXXK0Ox;.             "
      "                                    "
      "...,;:"
      "lk0XXNNXNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
      "'''''.......'''';::"
      "cxkOOO00000000000000000000000KKKKXXXXXXXXXXXXXXXXXXX0d;;:.              "
      "                                        "
      ".'cxkOKXNNNNNXNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
      "''''........'''';::"
      "lxkOO0000000000000000000000000KKKXXXXXXXXXXXXXXXXXKOd;...               "
      "                                         "
      ".',;lOKNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXNNNXXXXXXXXXXXXXXXXXXXXX\n"
      "'...........'''':ccoxOOO0000000000000000000000000KKKKXXXXXXXXXXXXKOOkdc,"
      ".                       ..                                     "
      "..:x0XXXNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXNNXXXXXXXXXXXXXXXXXXXXXX\n"
      "lc::;,,'...'.''':ccoxOOO0000000000000000000000000KKKKXXXXXXXXXXXX0o:,.. "
      "                                                                 "
      ".;d0XXNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
      "lllooooo:..,''',clcoxOOO0000000000000000000000000KKKKXXXXXXXXXXXKk;...  "
      "                                                                 "
      "..'lkKXNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
      "...''',,,..,''',llcokOOO0000000000000000000000000KKKKXXXXXXXXXXKk:.     "
      "                                                                   "
      ".'dKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
      "...........'''.;llldkOOO0000000000000000000000000KKKXXXXXXXXXXXKx,.     "
      "                                                                    "
      ".cOXNNNNNNNNNNNNNNNNNNNNNNXXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
      "...........'''':ooldkkOO000000000000000000000000KKKXXXXXXXXXXXXXO:.     "
      "                         .........                                  "
      ".,o0XNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKK\n"
      "...........'''':doldkOO00000000000000000000000KKKKKXXXXXXXXXXXXKOc...   "
      "                      ..............                                "
      "..cOXNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKK\n"
      "...........'''':olldkOO000000000000000000000000KKKKXXXXXXXXXXXXKkc'...  "
      "                    ...'',,,,,,'......                               "
      ".:OXNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKK\n"
      "..........'''''.,;cdkOO000000000000000000000000KKKKXXXXXXXXXXXKkl,'....."
      ".....             ...';;:::::::;,,'....                             "
      "..;kXNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKK\n"
      "...........''''..'cdkOO00000000000000000KKKKKKKKKKKXXXXXXXXXXX0d;'''...."
      "......           ...,:clllollllc::;,'........                       "
      "..;OXNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKK\n"
      "...........'''...'cxkOO0000000000000000KKKKKKKKKKKXXXXXXXXXXXX0xlc;'...."
      "'''...............';cloodddooooolcc:;'.....                         "
      "..:ONNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXKKKKKKKKKK0000000000\n"
      "........ "
      "..'''...,cxkOO00000000000000KKKKKKKKKKKKKXXXXXXXXXXXK0Odc;,,'',;;,,'...."
      ".......',;codddxxxdddddoolc:,'.....                       "
      "...c0NNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXKKKKKKK00000000000000\n"
      "...........'''...,lxkOO00000000000000KKKKKKKKKKKKXXXXXXXXXXXXXXKxc;;;;;:"
      "c:;;,',;;;,'..'',:coddxxxxxxxxdddool:;,'....                       "
      "...oKNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXKKKKKKK000000000000000\n"
      "'.........'''....;lxkOO0000000000000000KKKKKKKKKKXXXXXXXXXXXXXXKk:;cl:;"
      "clc:;:cccccc;,,,;:codxxxkkkxxxxxdddolc:,'...                         "
      ".;kNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXKKKKKKKK00000000OOOOOOOO\n"
      "'''.......''''...;lxOOO0000000000000000KKKKKKKKKKXXXXXXXXXXXXXXX0l;"
      "lkdcodollodoodxdllcclodxxkkkkkkkkxxxxddolc:,'....                      "
      "...;kNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXKKKKKKKK0000000OOOOOOOOOO\n"
      "'''..'.'..''''...;"
      "okOOO00000000000KKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXkcdKOkkOOOOOOOO00OOkkkkOk"
      "kOkkkkkkkkkxxxddoc:;,.........                 "
      "....:ONNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXKKKKKKKK000000OOOOOOOOOOOO\n"
      "'''......'''''...;"
      "okOOO00000000KKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXKxkKKKKKKKKKKKKXXKKKK000O"
      "OOOOkkkkkkkkxxdolc:,'....   ..                 "
      "....lKNNNNNNNNNNNNNNXXXXXXXXXXXXXXXKKKKKKKKK000000OOOOOOOOOOOOO\n"
      "''.......''''...';"
      "okOO00000000KKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXX000KKKKKKXXXXXXXXXXKK00O"
      "OOOOkkkkkkkxxddol:;,'...                       "
      "....dXNNNNNNNNNNNNNXXXXXXXXXXXXXXXXKKKKKKK000000OOOOOOOOOOOOOOO\n"
      "'.........'''...':"
      "dkOO00000000KKKKKKKKKKKKKKKKKKXXXXXXXXNNNNNNXNNXK00KKKKKKXXXXXXXXXXKK00O"
      "OOOkkkkkkxxxddoolc;,'...                    "
      "......;ONNNNNNNNNNNNNNXXXXXXXXXXXXXXXXKKKKKK00000OOOOOOOOOOOOOOOOO\n"
      "..........'.'...':"
      "dkOO00000000000KKKKKKKKKKKKKKKXXXXXXNNNNNNXXXXNXK000KKXXXXXXXXXXXXXKK000"
      "OOOOkkkkxxxxddooolc:;,'...                "
      "....''..cKNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXKKKKKK0000OOOOOOOOOOOOOOOOOO\n"
      "......  "
      "........':"
      "dkOO00000000000KKKKKKKKKKKKKKKXXXXXXNNNNNNNXXXNXX00KKKXXXXXXXXXXXXXKK000"
      "0OOOkkkkkxxxdoooollllcc:;'...         "
      ".....''..,;"
      "ckNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXKKKKK00000OOOOOOOOOOOOOOOOOO\n"
      "'...............'"
      "cdkOO00000000000KKKKKKKKKKKKKKKXXXXXXNNXNNNNNNNNXXKKKKXXXXXXXXXXXXXKKK00"
      "000OOOOkkkkxxdooolllllllcc:,'...     "
      "......',,'',"
      "ckXNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXKKKKKK0000OOOOOOOOOOOOOOOOOOO\n"
      "''''............,"
      "cxkOO00000000000KKKKKKKKKKKKKKKXXXXXXNXXXXXNNNNNXKKKKKKKKKKKKKKKKKKK0000"
      "0000OOOOkkkkxddolllllllllcc:;...    "
      "......',;;,,;"
      "lONNNNNNNNNNNNNNNNNXXXXXXXXXXXXXKKKKKK00000OOOOOOOOOOOOOOOOOOO\n"
      "''........''....,"
      "cxkOO00000000000KKKKKKKKKKKKKKXXXXXXXXXXXNNNNNNNX0O00KKKKKKKKK00000000OO"
      "OOOOkkkxxxdddolllllllllllllc;'...  "
      "........,;:;;;"
      "l0NNNNNNNNNNNNNNNNNXXXXXXXXXXXXXKKKKK00000OOOOOOOOOOOOOOOOOOOO\n"
      "''.......''''...,"
      "lxkOO00000000000KKKKKKKKKKKKKKXXXXXXXXNNNNNNNNNNXOxxxkkOOO0000000Okxddol"
      "llloooooollcccc::ccllloooolc:,'.. "
      "..','....';::;:"
      "dKNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXKKKKK0000OOOOOOOOOOOOOOOOOOOOO\n"
      "''.......''''...;"
      "lxOO00000000000KKKKKKKKKKKKKKKXXXNNNXNNNNNNNNNNNNKOxdooolloxkO0Okxoc;,,;"
      "cloxxxxxdolcc::::cloooooollcc;'.....,;,....;:::;"
      "l0NNNNNNNNNNNNNNNNNNXXXXXXXXXXXXKKKKKK0000OOOOOOOOOOOOOOOOOOOOO\n"
      ".........''''...;"
      "okOO00000000000KKKKKKKKKKKKKKKXXXNNNNNNNNNNNNNNNNNXKOkkxoolodO00kdl;,;"
      "codkkOOkxxdolcc:;;:loddddoollc:;'....';:;'.,;:::;;"
      "xNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXKKKKK00000OOOOOOOOOOOOOOOOOOOOO\n"
      ".........'''....;"
      "okOO0000000000KKKKKKKKKKKKKKKXXXXNNNNNNNNNNNNNNNNNNXOxdolllldOKKOdc::"
      "coxxdxxkxdolc:;,,;:lodxxdddoolc:;,'''',;;;,;cc:::;"
      "o0NNNNNNNNNNNNNNNNNNXXXXXXXXXXXXKKKKKK00000OOOOOOOOOOOOOOOOOOOOO\n"
      "....''...';"
      "okOO000000000KKKKKKKKKKKKKKKKXXXXNNNNNNNNNNNNNNNNNNXOolcclodxOKKOxlclodx"
      "kxxdoolcc::::coddxxxxdddoollc:;,'',;:;;;:cccc:"
      "l0NNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXKKKKKK0000OOOOOOOOOOOOOOOOOOOOOO\n"
      "..........''...':"
      "okOO000000000KKKKKKKKKKKKKKKKXXXNNNNNNNNNNNNNNNNNNNX0Okxddxxk0KKOxooodxx"
      "kOOkkxddddddxxkkkxxxxxddoollc::;,',::::::ccc;:"
      "ONNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXKKKKKK0000OOOOOOOOOOOOOOOOOOOOOO\n"
      "''..........'.',:"
      "dkOO000000000KKKKKKKKKKKKKKKKXXXNNNNNNNNNNNNNNNNNNNNK00000000KK0kxdddxxk"
      "kO000000OO000OOOkkxxxxddollcc::;,,,::::::cc::"
      "dXNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXKKKKKK000OOOOOOOOOOOOOOOOOOOOOOO\n"
      "''.........''',;"
      "cdkOO000000000KKKKKKKKKKKKKKKXXXXNNNNNNNNNNNNNNNNNNNNXKKKKKKKKKK0kxddxxx"
      "kO0KKKKKKKKKK00OOOkkkxxdoolcc:::;;,;:::::::"
      "cccxXNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXKKKKKK0000OOOOOOOOOOOOOOOOOOOOOO\n"
      "'''''.....''',;;"
      "lxkOO0000000000000KKKKKKKKKKKXXXNNNNNNNNNNNNNNNNNNNNNXKKKKKKKKKK0kxdddxk"
      "kO0KKKKKKKKKK000OOkkxxddollcc:::;;;;:cccc::cc:"
      "l0NNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXKKKKKK0000OOOOOOOOOOOOkkOOOOOOOO\n"
      "'''''....'''',;:"
      "lxkOO000000OOOOOOOkkkkkkkkOOOO0000KKKKKKKKKXXXXXXXXXXXKKKKKKKKKKOkxddxxk"
      "kxkO0KKKKK00000OOkkxxddollcc:::::;;;:cccccccc:"
      "l0NNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXKKKKKK0000OOOOOOOOOOkkkkkOOOOOOO\n"
      "''''''...''',;::"
      "oxOO0000OOOOOkkkkkkxxxkxxxxxxxxxxxkxxkkkkkkkkkkkOOOOOOO000000KK0Okkxxkkk"
      "xollxO0000OOOOOkkxxddooollcc:::::;;;;:"
      "cccccccco0XNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXKKKKKK0000OOOOOOOOOkkkkkkkkOOO"
      "OO\n"
      "'''.''...''',::"
      "cokOO00OOOOOOkkkkkkxxxxxxxkkkkkkkkkkkkxxxxkkkkxxkkkkkkkkOOOO0KKK0OOkkkkk"
      "doc;;cdkkOOkkkkxxddooooolllcc:::::;;;;::"
      "cccccccoOXNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXKKKKK00000OOOOOOOOOkkkkkkkkOOOO"
      "O\n"
      "ccc::,..'''';"
      "cccokOOOOOOOOkkkkkkkkkxddxxkkkkkkkkkkkkkkxxxxkkkkkkkkkkxxxxkkkO0K0Okxdoc"
      ":;,,,,;codxxxxxxxddoolllllollcc:::;;;,,;;::"
      "ccccccld0XNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXKKKKK00000OOOOOOOOkkkkkkkkkkOOOO"
      "\n"
      "ooool;..'''':"
      "llldkOOOOOOOOkkkkkkkkkxdddxkkkkkkkkkkkkkkkxxxxkkkkkkkkxxxdxxkkkkkxdl:,'."
      ".',;:clodddddxxxxddoollloodolc:::;;;;,,;;;::"
      "cccccclx0NNNNNNNNNNNNNNNNNNNNXXXXXXXXXXKKKKK00000OOOOOOOkkkkkkkkkkkOOOO"
      "\n"
      "'''......'''"
      "cdoldkOOOkddxxxxxxxddddxddddxxkxxkOOkkkkkkkxxdxkkOOkkkkxxxdxxkkkkxdlcc:;"
      "::cccllollooooddddddddoooooddlc:;;;;,,,,,;;:::"
      "ccccclldkOKNWNNNNNNNNNNNNNNNXXXXXXXXXXKKKKK00000OOOOOOkkkkkkkkkkkkOOOO\n"
      "''.........'"
      "ldoodkOOxclkkkOOkkxxxxxxddddddxxxxkkkkkkkkkxxddxkOOkkkkkxxdxxkkkkkxddddd"
      "ddoolllllcc:::loooddxxdocloolc:;;;,,,',,,;;:::cccclllccc:"
      "cx0XNNNNNNNNNNNNXXXXXXXXXXXKKKKK0000OOOOkkkkkkkkkkkkkkkOOOO\n"
      "'........'.,"
      "lxooxOOkllOOOOOOkkkkkkkkkxxxxxxxxxxxxxxxxxxxxdddkOOkkkkkkxddkkOkkkxddxxx"
      "dolcccc::;..'':odoodxxdlccolc:;;,,,''',,,;;:::cccccclcll:...,"
      "cdOXNNNNNNNNNNXXXXXXXXKKKKKK0000OOOOkkkkkkkkkkkkkkkOOOO\n"
      ".........'.,"
      "oxooxOOxcx0OOOOOOkkkkkkkkkxxxxxxxxxxxxxxxxxdxxddxxkkkkkkkxxxxOOkkkxdxkOO"
      "kdxddxdll:,;:codxxxxxxlc:cllc:;,'''''',,;;;::cccccccllllc,     "
      ".;lddxxxkkOO0000KKKKKKKKK00000OOOOkkkkkkkkkkkkkkkkOOO\n"
      "...........'"
      "colokOOooO0OOOOOkkOkkkkkkkxxxxxxxxxkkkxxxxxxxxxdddxxxxxkkxxxkOOkkkxxkxxk"
      "kxkkkkxollcclodxxxxxxdl:::cc:;,''.'''',;;;::cccccccllllll'        "
      "....,;;;::ccccllooodoooooodddoodddddddxxxxxxkkkkkO\n"
      "............',;"
      "oO0xlx000OOOOkkOkkkkkkkxxxxxxxxkkkkxxxxxxxxxxdddxxxxxxxxxkkkkxxxxkkxxxdd"
      "xOOkdlllllodxxxkxxoc:::c:;,'''''',,;;:::cccccccclllloc.            "
      "..',;:ccc::ccccccccccllllllllooooooooodddddxxx\n"
      "..............,"
      "d0Odlx000OOOOOOOkkkkkkkkxkkxxkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxddxkkxkxx"
      "xxdollllllodxxxxxdoc::::;,'''''',,;;:::cccccccllllloo;.                "
      "..';;:cclllllllllllllllllooooooooodddddddd\n"
      "'..   "
      "........;"
      "x0Odlk0O0OOOOOOOkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxdoc;"
      "cxkxddoolllllllodxkkkkxdl:::::;,''''',,;::ccccllllllllllool'            "
      "         ..';:cccccccccccccccllllllooooddddddxx\n"
      "..............;"
      "x00dlk000OOOOOOOkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxdl:'...."
      "lOOkxdoooddxxkkOOOOkxdl:,;;;;,''...',;:cclllooooolllloood:.             "
      "           ...',;::::::::cccccclllooooddddxxxx\n"
      "..............:k0Oolk000OOOOOOOkkkkkkkkkkkkkkkkkkxxxxxxkxxxxxxxxxxxxxdl:"
      ",'..     .,x000OkkOOOO0000Okxxoc,''',,''.....';:clooddddddoooooodo;.    "
      "                         ...',,,;;:::::::cclllooodddxxxx\n"
      "..............:k0dcd0000OOOOOOOkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxdoc;,..."
      "          .ck000000000OOOkxolc;'.....'......,:cloddxxxxxddddooooc'.     "
      "                            ....',;;:;;;::::ccclloodddxx\n"
      "..............:kkllO0000OOOOOOOkkkkkkkkkkkkkkkkkkxxkkkxxxxxxoc;,....    "
      "           .cxkkOOOkkxxdolc;;,............';:lodxxxxxxxxxdddddl;.       "
      "                               ....,,;;;;;;:::::cclloodd\n"
      "..............:kdcx000000OOOOOkkkkkkkkkkkkkkkkkxxxxkkxxxxdc,..          "
      "           ..,clooolc:;,,''.............';:codxkkkkkkkxxxxxxdc'.        "
      "                                 .....',,;;;:::::::ccllo\n"
      "........''....:kdlk0000OOOOOOOOkkkkkkkkkkkkkkkxxxxxxxxoc;...            "
      "             ...:ddool::;,,'''.''',,,,;:clodxkkkkkkkkkkkkkko,.          "
      "                                  ........',;;;;;;;;:::c\n"
      ".........'....ckdlk0000OOOOOOOOkkkkkkkkkkkkkkxxxxxxdl;....              "
      "           ..   ;OKKKK000OkkxxdoooooooodxkkOOOOOOOOOOOOOkd;.            "
      "                                .............'..........\n"
      "..........lOxcx000OOOOOOOOkkkkkkkkkkkkkkxxxxxdc,......                  "
      "      ..    'xKXKXXKKKKKKK000000000000000000000000ko;.                  "
      "                               ...................''\n"
      "........,,'',:x0xcd000OOOOOOOkkkkkkkkkkkkkkxxxxdc,....                  "
      "          .     .:OXXXXXXXXXXXKKKKKKXXXXXXKKKKKKKK0ko:.                 "
      "                                    ....  ..      .....'\n"
      ",;:::ccloddddxOOdcd0OOOOOOOOOkkkkkkkkkkkkkxkxxo,.. ..                   "
      "                 .;kKXXXXXXXXXXXKXXXXXXXXXXXXKKKKOo,                    "
      "                                                     ...\n"

  );

  return 0;
}
